# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(:name_id => '1', :password => 'pass', :name => '竹内 真')
User.create(:name_id => '2', :password => 'pass', :name => '猪狩 丈治')
User.create(:name_id => '3', :password => 'pass', :name => '山口 俊一')
User.create(:name_id => '4', :password => 'pass', :name => '宮本 由三佳')
User.create(:name_id => '5', :password => 'pass', :name => '北田 えりか')
User.create(:name_id => '6', :password => 'pass', :name => '村井　優太')
User.create(:name_id => '7', :password => 'pass', :name => '有村　友秀')
User.create(:name_id => '8', :password => 'pass', :name => '山田　晃士')
User.create(:name_id => '9', :password => 'pass', :name => '原田　和磨')
User.create(:name_id => '10', :password => 'pass', :name => '國領　祐子')
User.create(:name_id => '11', :password => 'pass', :name => '茜屋　渉')
User.create(:name_id => '12', :password => 'pass', :name => '阿部　涼平')
User.create(:name_id => '13', :password => 'pass', :name => '土屋　正徳')
User.create(:name_id => '14', :password => 'pass', :name => '菅間　弘嗣')
User.create(:name_id => '15', :password => 'pass', :name => '佐藤　大介')
User.create(:name_id => '16', :password => 'pass', :name => '柳下　優介')
User.create(:name_id => '17', :password => 'pass', :name => '堤　克靖')
User.create(:name_id => '18', :password => 'pass', :name => '田中　邦典')
User.create(:name_id => '19', :password => 'pass', :name => '滝野　雅俊')
User.create(:name_id => '20', :password => 'pass', :name => '甘利　大')
User.create(:name_id => '21', :password => 'pass', :name => '米須　真由美')
User.create(:name_id => '22', :password => 'pass', :name => '新井　彩')
User.create(:name_id => '23', :password => 'pass', :name => '櫻田　拓也')
User.create(:name_id => '24', :password => 'pass', :name => '皆川　拓也')
User.create(:name_id => '25', :password => 'pass', :name => '渡邊　磨耶')
User.create(:name_id => '26', :password => 'pass', :name => '山添　奈穂子')
User.create(:name_id => '27', :password => 'pass', :name => '大木　裕子')
User.create(:name_id => '28', :password => 'pass', :name => '村中　亮介')
User.create(:name_id => '29', :password => 'pass', :name => '土肥　直樹')
User.create(:name_id => '30', :password => 'pass', :name => '平田　雅弓')
User.create(:name_id => '31', :password => 'pass', :name => '根岸　周一')
User.create(:name_id => '32', :password => 'pass', :name => '笹島　大和')
User.create(:name_id => '33', :password => 'pass', :name => '牧田　直也')
User.create(:name_id => '34', :password => 'pass', :name => '武田　拓也')
User.create(:name_id => '35', :password => 'pass', :name => '山田　祥')
User.create(:name_id => '36', :password => 'pass', :name => '渡邉　貴之')
User.create(:name_id => '37', :password => 'pass', :name => '原田　芽依')
User.create(:name_id => '38', :password => 'pass', :name => '渡辺　圭')
User.create(:name_id => '39', :password => 'pass', :name => '白石　由香里')
User.create(:name_id => '40', :password => 'pass', :name => '山本　惇')
User.create(:name_id => '41', :password => 'pass', :name => '古金　美香')
User.create(:name_id => '42', :password => 'pass', :name => '福田　貴博')
User.create(:name_id => '43', :password => 'pass', :name => '青柳　隆弘')
User.create(:name_id => '44', :password => 'pass', :name => '任 美璇')
User.create(:name_id => '45', :password => 'pass', :name => '濱口　結')
User.create(:name_id => '46', :password => 'pass', :name => '崔　勲')
User.create(:name_id => '47', :password => 'pass', :name => '早川　裕子')
User.create(:name_id => '48', :password => 'pass', :name => '柳沢　英俊')
User.create(:name_id => '49', :password => 'pass', :name => '金子　龍樹')
User.create(:name_id => '50', :password => 'pass', :name => '大村　基記')
User.create(:name_id => '51', :password => 'pass', :name => '渡邉　直己')
User.create(:name_id => '52', :password => 'pass', :name => '吉高　陸')
User.create(:name_id => '53', :password => 'pass', :name => '斉藤　直之')
User.create(:name_id => '54', :password => 'pass', :name => '原田　真衣')
User.create(:name_id => '55', :password => 'pass', :name => '関戸　裕介')
User.create(:name_id => '56', :password => 'pass', :name => '山本　雄大')
User.create(:name_id => '57', :password => 'pass', :name => '畑堀　文菜')
User.create(:name_id => '58', :password => 'pass', :name => '原口　久美子')
User.create(:name_id => '59', :password => 'pass', :name => '鈴木　夏実')
User.create(:name_id => '60', :password => 'pass', :name => '後藤　亜梨紗')
User.create(:name_id => '61', :password => 'pass', :name => '竹内　郷平')
User.create(:name_id => '62', :password => 'pass', :name => '近藤　夏実')
User.create(:name_id => '63', :password => 'pass', :name => '斉藤　直之')
User.create(:name_id => '64', :password => 'pass', :name => '木枝　博道')
User.create(:name_id => '65', :password => 'pass', :name => '田島　佳奈子')
User.create(:name_id => '66', :password => 'pass', :name => '溝井　美穂')
User.create(:name_id => '67', :password => 'pass', :name => '柳　勇貴')
User.create(:name_id => '68', :password => 'pass', :name => '川島  唯人')
User.create(:name_id => '69', :password => 'pass', :name => '田原　一樹')
User.create(:name_id => '70', :password => 'pass', :name => '冨永 将司')
User.create(:name_id => '71', :password => 'pass', :name => '青木 桂人')
User.create(:name_id => '72', :password => 'pass', :name => '泉澤 亘')
User.create(:name_id => '73', :password => 'pass', :name => '丹後　彩乃')
User.create(:name_id => '74', :password => 'pass', :name => '鶴田　啓')
User.create(:name_id => '75', :password => 'pass', :name => '坂詰　幸一郎')
User.create(:name_id => '76', :password => 'pass', :name => '小川　祐輝')
User.create(:name_id => '77', :password => 'pass', :name => '鈴木　恵里')
User.create(:name_id => '78', :password => 'pass', :name => '花﨑　ななみ')
User.create(:name_id => '79', :password => 'pass', :name => 'Kolibarova Barbora')
User.create(:name_id => '80', :password => 'pass', :name => '村松　純太')
User.create(:name_id => '81', :password => 'pass', :name => '道前　優弥')
User.create(:name_id => '82', :password => 'pass', :name => '細谷　大地')
User.create(:name_id => '83', :password => 'pass', :name => '竹田　直也')
User.create(:name_id => '84', :password => 'pass', :name => '小林　貴之')
User.create(:name_id => '85', :password => 'pass', :name => '木村　麻衣')
User.create(:name_id => '86', :password => 'pass', :name => '冨岡　恵')
User.create(:name_id => '87', :password => 'pass', :name => '塩島　杏奈')



Comment.create(:comment => 'こんにちは', :user_id => 1, :room_id => 1)
Comment.create(:comment => 'おはよう', :user_id => 2, :room_id => 1)
Comment.create(:comment => 'おやすみ', :user_id => 1, :room_id => 1)

Room.create(:room_name => '竹内 真&猪狩 丈治')
Room.create(:room_name => '竹内 真&山口 俊一')
# Room.create(:room_name => '丹後　彩乃&川島　唯人')
#
Relationship.create(:room_id => 1, :user_id => 1)
Relationship.create(:room_id => 1, :user_id => 2)
Relationship.create(:room_id => 2, :user_id => 1)
Relationship.create(:room_id => 2, :user_id => 3)
# Relationship.create(:room_id => 3, :user_id => 1)
# Relationship.create(:room_id => 3, :user_id => 4)
